name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install -y libunwind-dev
    - name: Install Meta's Rust toolchain
      run: ./.github/scripts/install_meta_rust.sh 1.64.0
      shell: bash
    - name: Build
      run: cargo +meta-1.64.0 build
