name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTUP_DIST_SERVER: "http://rust-dists.s3-website.us-west-1.amazonaws.com"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install -y libunwind-dev patchelf
    - name: Install Meta's Rust toolchain
      run: ./.github/scripts/install_meta_rust.sh 1.64.0-meta
      shell: bash
    - name: Build
      run: RUSTC=~/.rustup/toolchains/1.64.0-meta/bin/rustc cargo build
